#!/usr/bin/env node
/**
 * Generates 25-30 quiz questions per HSK1 lesson and writes them back to the lesson JSON files.
 * Usage: node scripts/generateLessonQuizzes.js
 */
const fs   = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../data/hsk1');

// ── Quiz data for all 15 lessons ──────────────────────────────────────────────
const ALL_QUIZZES = {

  1: [
    { question: "What does 你好 mean?", type: "multiple_choice", correct: "Hello", options: ["Goodbye", "Hello", "Thank you", "Sorry"] },
    { question: "How do you say 'Goodbye' in Chinese?", type: "multiple_choice", correct: "再见", options: ["你好", "谢谢", "再见", "对不起"] },
    { question: "What does 谢谢 mean?", type: "multiple_choice", correct: "Thank you", options: ["Sorry", "You're welcome", "Thank you", "Hello"] },
    { question: "Which word means 'I / me'?", type: "multiple_choice", correct: "我", options: ["你", "我", "他", "她"] },
    { question: "What does 是 mean?", type: "multiple_choice", correct: "Am / Is / Are (to be)", options: ["Have", "Am / Is / Are (to be)", "Go", "Want"] },
    { question: "How do you say 'You are a teacher.' in Chinese?", type: "multiple_choice", correct: "你是老师。", options: ["我是老师。", "你是老师。", "他是老师。", "你有老师。"] },
    { question: "What particle makes a statement into a yes/no question?", type: "multiple_choice", correct: "吗", options: ["呢", "的", "吗", "了"] },
    { question: "Fill in: 我___老师。(I am a teacher)", type: "multiple_choice", correct: "是", options: ["在", "有", "是", "和"] },
    { question: "How do you say 'I am not a student.'?", type: "multiple_choice", correct: "我不是学生。", options: ["我没是学生。", "我不是学生。", "我不有学生。", "不我是学生。"] },
    { question: "What does 的 do in 我的名字?", type: "multiple_choice", correct: "Shows possession (my name)", options: ["Makes a question", "Shows past action", "Shows possession (my name)", "Connects nouns"] },
    { question: "What does 叫 mean?", type: "multiple_choice", correct: "To be called / Named", options: ["To know", "To be called / Named", "To like", "To have"] },
    { question: "How do you ask 'What is your name?'", type: "multiple_choice", correct: "你叫什么名字？", options: ["你是谁？", "你叫什么名字？", "你有名字吗？", "你是什么名字？"] },
    { question: "What does 她 mean?", type: "multiple_choice", correct: "She / Her", options: ["He / Him", "She / Her", "They", "You"] },
    { question: "What does 也 mean?", type: "multiple_choice", correct: "Also / Too", options: ["Still", "Already", "Also / Too", "Very"] },
    { question: "How do you say 'She is also a teacher.'?", type: "multiple_choice", correct: "她也是老师。", options: ["她很是老师。", "她也是老师。", "她都是老师。", "她是也老师。"] },
    { question: "What does 好 mean?", type: "multiple_choice", correct: "Good / Well", options: ["Bad", "Good / Well", "Big", "Small"] },
    { question: "你好吗？means:", type: "multiple_choice", correct: "How are you?", options: ["Are you good?", "Do you have it?", "How are you?", "Where are you?"] },
    { question: "What does 很 mean?", type: "multiple_choice", correct: "Very", options: ["Not", "Also", "Very", "All"] },
    { question: "我很好。means:", type: "multiple_choice", correct: "I am very well.", options: ["I have a lot.", "I am very well.", "I am not well.", "I also am good."] },
    { question: "How do you say 'What about you?' (short form)?", type: "multiple_choice", correct: "你呢？", options: ["你是？", "你呢？", "你吗？", "你的？"] },
    { question: "What is 老师?", type: "multiple_choice", correct: "Teacher", options: ["Student", "Doctor", "Teacher", "Friend"] },
    { question: "Fill in: 你是学生___？(Are you a student?)", type: "multiple_choice", correct: "吗", options: ["呢", "的", "吗", "不"] },
    { question: "What does 对 mean?", type: "multiple_choice", correct: "Correct / Right", options: ["Wrong", "Correct / Right", "Good", "Bad"] },
    { question: "How do you say 'She is not a student.'?", type: "multiple_choice", correct: "她不是学生。", options: ["她没有学生。", "她不是学生。", "她不在学生。", "她是不学生。"] },
    { question: "What does 不 do before 是?", type: "multiple_choice", correct: "Makes it negative: 'is not'", options: ["Makes it a question", "Makes it past tense", "Makes it negative: 'is not'", "Has no effect"] },
    { question: "Translate: 'My name is Xiao Ming.'", type: "multiple_choice", correct: "我叫小明。", options: ["我的名字很好。", "我是叫小明。", "我叫小明。", "名字我叫小明。"] },
    { question: "What does 再见 literally mean?", type: "multiple_choice", correct: "See you again", options: ["Go away", "See you again", "Good night", "Take care"] }
  ],

  2: [
    { question: "What does 一 mean?", type: "multiple_choice", correct: "One", options: ["One", "Two", "Three", "Four"] },
    { question: "How do you say '7' in Chinese?", type: "multiple_choice", correct: "七", options: ["六", "七", "八", "九"] },
    { question: "What does 零 mean?", type: "multiple_choice", correct: "Zero", options: ["Zero", "Ten", "Hundred", "One"] },
    { question: "How do you say '10' in Chinese?", type: "multiple_choice", correct: "十", options: ["百", "千", "十", "万"] },
    { question: "What does 岁 mean?", type: "multiple_choice", correct: "Years old", options: ["Year", "Age", "Years old", "Month"] },
    { question: "How do you say 'I am 18 years old.'?", type: "multiple_choice", correct: "我十八岁。", options: ["我是十八岁。", "我有十八岁。", "我十八岁。", "十八岁我。"] },
    { question: "What does 多大 ask?", type: "multiple_choice", correct: "How old (for adults)", options: ["How many", "How big", "How old (for adults)", "How much"] },
    { question: "What does 几岁 ask?", type: "multiple_choice", correct: "How old (for children)", options: ["How many years", "How old (for children)", "How many people", "What year"] },
    { question: "How do you say '15'?", type: "multiple_choice", correct: "十五", options: ["五十", "十五", "一五", "五一"] },
    { question: "What is 两 used for instead of 二?", type: "multiple_choice", correct: "Before measure words (两个, 两本)", options: ["Counting in sequence", "Before measure words (两个, 两本)", "In phone numbers", "All situations"] },
    { question: "How do you say 'two people' in Chinese?", type: "multiple_choice", correct: "两个人", options: ["二个人", "两个人", "两人个", "人两个"] },
    { question: "What is 个?", type: "multiple_choice", correct: "General measure word", options: ["Measure word for books", "General measure word", "Measure word for drinks", "Measure word for family"] },
    { question: "How do you say '21'?", type: "multiple_choice", correct: "二十一", options: ["二十一", "一十二", "十二一", "二一十"] },
    { question: "What does 几 ask?", type: "multiple_choice", correct: "How many (for small numbers)", options: ["How much money", "How many (for small numbers)", "Which one", "What time"] },
    { question: "What measure word for 'people' in family context?", type: "multiple_choice", correct: "口", options: ["个", "人", "口", "位"] },
    { question: "How do you say 'three people'?", type: "multiple_choice", correct: "三个人", options: ["三人", "三个人", "人三个", "个三人"] },
    { question: "What number is 九?", type: "multiple_choice", correct: "9", options: ["6", "7", "8", "9"] },
    { question: "How do you say 'five cups'?", type: "multiple_choice", correct: "五杯", options: ["杯五", "五杯", "五个杯", "五杯子"] },
    { question: "What is 百?", type: "multiple_choice", correct: "Hundred", options: ["Ten", "Hundred", "Thousand", "Ten thousand"] },
    { question: "How do you say 'How old are you?' to an adult?", type: "multiple_choice", correct: "你多大？", options: ["你几岁？", "你多大？", "你是几岁？", "你的年龄？"] },
    { question: "What number comes after 八?", type: "multiple_choice", correct: "九", options: ["七", "十", "九", "六"] },
    { question: "How do you say '100'?", type: "multiple_choice", correct: "一百", options: ["百一", "十十", "一百", "百"] },
    { question: "Fill in: 我___十六岁。(I am 16 years old)", type: "multiple_choice", correct: "No verb needed", options: ["是", "有", "在", "No verb needed"] },
    { question: "What does 多少 ask?", type: "multiple_choice", correct: "How many / How much (for large numbers)", options: ["How small", "How many / How much (for large numbers)", "How old", "How far"] },
    { question: "What is the correct order for '35'?", type: "multiple_choice", correct: "三十五", options: ["五三十", "三五十", "十三五", "三十五"] },
    { question: "What number is 四?", type: "multiple_choice", correct: "4", options: ["3", "4", "5", "6"] },
    { question: "Translate: 'She is 25 years old.'", type: "multiple_choice", correct: "她二十五岁。", options: ["她是有二十五岁。", "她二十五岁。", "二十五岁她。", "她很二十五岁。"] }
  ],

  3: [
    { question: "What does 今天 mean?", type: "multiple_choice", correct: "Today", options: ["Yesterday", "Tomorrow", "Today", "Day"] },
    { question: "What does 明天 mean?", type: "multiple_choice", correct: "Tomorrow", options: ["Yesterday", "Today", "Tomorrow", "Next week"] },
    { question: "What does 昨天 mean?", type: "multiple_choice", correct: "Yesterday", options: ["Yesterday", "Today", "Tomorrow", "Last week"] },
    { question: "What does 上午 mean?", type: "multiple_choice", correct: "Morning (A.M.)", options: ["Afternoon", "Evening", "Morning (A.M.)", "Noon"] },
    { question: "What does 下午 mean?", type: "multiple_choice", correct: "Afternoon (P.M.)", options: ["Morning", "Afternoon (P.M.)", "Evening", "Midnight"] },
    { question: "What does 晚上 mean?", type: "multiple_choice", correct: "Evening / Night", options: ["Afternoon", "Morning", "Evening / Night", "Noon"] },
    { question: "今天几号？means:", type: "multiple_choice", correct: "What's the date today?", options: ["What time is it?", "What's the date today?", "What day is today?", "What month is it?"] },
    { question: "What is the correct date order in Chinese?", type: "multiple_choice", correct: "Year, Month, Date", options: ["Date, Month, Year", "Month, Date, Year", "Year, Month, Date", "All the same as English"] },
    { question: "What does 月 mean?", type: "multiple_choice", correct: "Month", options: ["Day", "Year", "Month", "Week"] },
    { question: "What does 号 mean?", type: "multiple_choice", correct: "Date number / Day of month", options: ["Month", "Year", "Date number / Day of month", "Week"] },
    { question: "How do you say 'January 1st'?", type: "multiple_choice", correct: "一月一号", options: ["一号一月", "一月一号", "一日一月", "月一号一"] },
    { question: "What does 年 mean?", type: "multiple_choice", correct: "Year", options: ["Month", "Day", "Year", "Week"] },
    { question: "Fill in: 今天___月___号？(What's the date?)", type: "multiple_choice", correct: "几 / 几", options: ["什么 / 什么", "几 / 几", "多少 / 多少", "哪 / 哪"] },
    { question: "How do you say 'this morning'?", type: "multiple_choice", correct: "今天上午", options: ["今天下午", "上午今天", "今天上午", "今天早上午"] },
    { question: "What does 点 mean in time expressions?", type: "multiple_choice", correct: "O'clock / Hour", options: ["Minute", "Second", "O'clock / Hour", "Half"] },
    { question: "What does 分 mean in time expressions?", type: "multiple_choice", correct: "Minute", options: ["Hour", "Minute", "Second", "Half"] },
    { question: "How do you say '3:15'?", type: "multiple_choice", correct: "三点十五分", options: ["三点十五", "十五分三点", "三时十五", "三点十五分"] },
    { question: "What does 半 mean in time?", type: "multiple_choice", correct: "Half (past)", options: ["Quarter past", "Half (past)", "Quarter to", "Almost"] },
    { question: "How do you say '7:30'?", type: "multiple_choice", correct: "七点半", options: ["七点三十", "七时半", "七点半", "半七点"] },
    { question: "Translate: 'yesterday evening'", type: "multiple_choice", correct: "昨天晚上", options: ["昨天下午", "明天晚上", "昨天上午", "昨天晚上"] },
    { question: "What is 下午三点?", type: "multiple_choice", correct: "3:00 PM", options: ["3:00 AM", "3:00 PM", "3 days", "3 months"] },
    { question: "What comes first: time of day (上午) or clock time (几点)?", type: "multiple_choice", correct: "Time of day first: 上午九点", options: ["Clock time first: 九点上午", "Time of day first: 上午九点", "Either order is fine", "No time of day needed"] },
    { question: "How do you say 'tomorrow afternoon'?", type: "multiple_choice", correct: "明天下午", options: ["下午明天", "明天上午", "明天下午", "明天晚上"] },
    { question: "What does 前 mean in time?", type: "multiple_choice", correct: "Before / Ago", options: ["After", "During", "Before / Ago", "Around"] },
    { question: "How do you say 'March 8th'?", type: "multiple_choice", correct: "三月八号", options: ["八月三号", "三号八月", "三月八号", "八号三月"] },
    { question: "What is 今年?", type: "multiple_choice", correct: "This year", options: ["Next year", "Last year", "This year", "Every year"] }
  ],

  4: [
    { question: "What does 家 mean?", type: "multiple_choice", correct: "Home / Family", options: ["House", "Home / Family", "Room", "Garden"] },
    { question: "What is 爸爸?", type: "multiple_choice", correct: "Dad", options: ["Mom", "Dad", "Brother", "Sister"] },
    { question: "What is 妈妈?", type: "multiple_choice", correct: "Mom", options: ["Grandma", "Aunt", "Mom", "Sister"] },
    { question: "What is 哥哥?", type: "multiple_choice", correct: "Older brother", options: ["Younger brother", "Older brother", "Older sister", "Younger sister"] },
    { question: "What is 姐姐?", type: "multiple_choice", correct: "Older sister", options: ["Younger sister", "Older brother", "Older sister", "Mom"] },
    { question: "What is 弟弟?", type: "multiple_choice", correct: "Younger brother", options: ["Older brother", "Younger brother", "Younger sister", "Son"] },
    { question: "What is 妹妹?", type: "multiple_choice", correct: "Younger sister", options: ["Older sister", "Younger sister", "Daughter", "Mom"] },
    { question: "What does 有 mean?", type: "multiple_choice", correct: "To have / There is", options: ["To be", "To want", "To have / There is", "To go"] },
    { question: "How do you say 'I have a brother.'?", type: "multiple_choice", correct: "我有哥哥。", options: ["我是哥哥。", "我有哥哥。", "我在哥哥。", "我的哥哥。"] },
    { question: "What is the negative form of 有?", type: "multiple_choice", correct: "没有", options: ["不有", "无有", "没有", "没是"] },
    { question: "How do you say 'I don't have a sister.'?", type: "multiple_choice", correct: "我没有姐姐。", options: ["我不有姐姐。", "我没有姐姐。", "我没是姐姐。", "我无姐姐。"] },
    { question: "What does 儿子 mean?", type: "multiple_choice", correct: "Son", options: ["Daughter", "Son", "Child", "Boy"] },
    { question: "What does 女儿 mean?", type: "multiple_choice", correct: "Daughter", options: ["Son", "Daughter", "Girl", "Sister"] },
    { question: "What measure word counts people in a family?", type: "multiple_choice", correct: "口", options: ["个", "口", "本", "杯"] },
    { question: "你家有几口人？means:", type: "multiple_choice", correct: "How many people are in your family?", options: ["Who is in your family?", "How many people are in your family?", "Where is your family?", "Do you have a family?"] },
    { question: "How do you say 'My family has 4 people.'?", type: "multiple_choice", correct: "我家有四口人。", options: ["我家有四个人。", "我的家四口人。", "我家有四口人。", "四口人我家有。"] },
    { question: "What is 两 used with instead of 二?", type: "multiple_choice", correct: "Before measure words: 两个, 两口", options: ["In counting sequences", "Before measure words: 两个, 两口", "Only for people", "Only for animals"] },
    { question: "What does 没有 contrast with?", type: "multiple_choice", correct: "有 (to have)", options: ["是 (to be)", "有 (to have)", "在 (to be at)", "做 (to do)"] },
    { question: "Translate: 'She has two sons.'", type: "multiple_choice", correct: "她有两个儿子。", options: ["她是两个儿子。", "她有二个儿子。", "她有两个儿子。", "两个儿子她有。"] },
    { question: "Which is correct for 'older sister'?", type: "multiple_choice", correct: "姐姐", options: ["妹妹", "姐姐", "弟弟", "哥哥"] },
    { question: "What is 爸爸妈妈 together?", type: "multiple_choice", correct: "Parents", options: ["Grandparents", "Parents", "Brothers and sisters", "Children"] },
    { question: "我有没有哥哥？is an example of:", type: "multiple_choice", correct: "A-not-A question pattern", options: ["A 吗 question", "A negative statement", "A-not-A question pattern", "A command"] },
    { question: "What does 他们 mean?", type: "multiple_choice", correct: "They (male or mixed)", options: ["You all", "We", "They (male or mixed)", "She/Her"] },
    { question: "How do you say 'Do you have a younger brother?'", type: "multiple_choice", correct: "你有弟弟吗？", options: ["你是弟弟吗？", "你有没有弟弟？", "你有弟弟吗？", "Both B and C are correct"] },
    { question: "What does 家人 mean?", type: "multiple_choice", correct: "Family members", options: ["Family friend", "Family members", "Home person", "Relative"] },
    { question: "Translate: 'My dad is a teacher.'", type: "multiple_choice", correct: "我爸爸是老师。", options: ["我的爸爸老师。", "我爸爸是老师。", "老师是我爸爸。", "我爸爸有老师。"] }
  ],

  5: [
    { question: "What does 吃 mean?", type: "multiple_choice", correct: "To eat", options: ["To drink", "To eat", "To want", "To buy"] },
    { question: "What does 喝 mean?", type: "multiple_choice", correct: "To drink", options: ["To eat", "To drink", "To taste", "To smell"] },
    { question: "What is 米饭?", type: "multiple_choice", correct: "Rice (cooked)", options: ["Bread", "Noodles", "Rice (cooked)", "Vegetable"] },
    { question: "What is 面条?", type: "multiple_choice", correct: "Noodles", options: ["Rice", "Noodles", "Bread", "Dumpling"] },
    { question: "What does 水 mean?", type: "multiple_choice", correct: "Water", options: ["Tea", "Coffee", "Milk", "Water"] },
    { question: "What is 茶?", type: "multiple_choice", correct: "Tea", options: ["Coffee", "Tea", "Milk", "Juice"] },
    { question: "What is 牛奶?", type: "multiple_choice", correct: "Milk", options: ["Tea", "Water", "Milk", "Coffee"] },
    { question: "What is 咖啡?", type: "multiple_choice", correct: "Coffee", options: ["Tea", "Coffee", "Juice", "Milk"] },
    { question: "What does 菜 mean?", type: "multiple_choice", correct: "Vegetable / Dish", options: ["Fruit", "Rice", "Vegetable / Dish", "Meat"] },
    { question: "What is 苹果?", type: "multiple_choice", correct: "Apple", options: ["Orange", "Apple", "Banana", "Grape"] },
    { question: "What does 想 mean?", type: "multiple_choice", correct: "To want / Would like", options: ["To have", "To want / Would like", "To think only", "To need"] },
    { question: "What is the measure word for drinks?", type: "multiple_choice", correct: "杯", options: ["个", "杯", "本", "口"] },
    { question: "How do you say 'a cup of tea'?", type: "multiple_choice", correct: "一杯茶", options: ["一个茶", "茶一杯", "一杯茶", "杯茶"] },
    { question: "How do you ask 'What would you like to eat?'", type: "multiple_choice", correct: "你吃什么？", options: ["你喝什么？", "你想什么？", "你有什么？", "你吃什么？"] },
    { question: "Translate: 'I want to drink water.'", type: "multiple_choice", correct: "我想喝水。", options: ["我喝水。", "我想喝水。", "我有水喝。", "我喝想水。"] },
    { question: "What comes after 想 in a sentence?", type: "multiple_choice", correct: "A verb (action word)", options: ["A noun", "A verb (action word)", "An adjective", "Nothing"] },
    { question: "How do you say 'two cups of coffee'?", type: "multiple_choice", correct: "两杯咖啡", options: ["二杯咖啡", "两个咖啡", "两杯咖啡", "咖啡两杯"] },
    { question: "Translate: '请喝茶。'", type: "multiple_choice", correct: "Please have some tea.", options: ["Do you want tea?", "I drink tea.", "Please have some tea.", "Tea, please give me."] },
    { question: "How do you say 'I don't want to eat noodles.'?", type: "multiple_choice", correct: "我不想吃面条。", options: ["我没想吃面条。", "我不吃面条。", "我不想吃面条。", "我想不吃面条。"] },
    { question: "What is the difference between 想 and 要?", type: "multiple_choice", correct: "想 is softer/more polite; both express want", options: ["They are identical", "想 is softer/more polite; both express want", "要 is softer", "想 is only for thinking"] },
    { question: "How do you say 'She wants to drink milk.'?", type: "multiple_choice", correct: "她想喝牛奶。", options: ["她喝牛奶想。", "她想牛奶喝。", "她想喝牛奶。", "她牛奶想喝。"] },
    { question: "什么 in 你吃什么？replaces:", type: "multiple_choice", correct: "The food you're asking about", options: ["The subject", "The verb", "The food you're asking about", "The time"] },
    { question: "How do you say 'Eat vegetables' as a phrase?", type: "multiple_choice", correct: "吃菜", options: ["喝菜", "吃水", "吃菜", "做菜"] },
    { question: "Translate: 'Do you drink coffee?'", type: "multiple_choice", correct: "你喝咖啡吗？", options: ["你有咖啡吗？", "你想咖啡吗？", "你喝咖啡吗？", "你吃咖啡吗？"] },
    { question: "How do you say 'I eat rice.'?", type: "multiple_choice", correct: "我吃米饭。", options: ["我喝米饭。", "我吃面条。", "我吃米饭。", "米饭我吃。"] }
  ],

  6: [
    { question: "What does 买 mean?", type: "multiple_choice", correct: "To buy", options: ["To sell", "To buy", "To pay", "To take"] },
    { question: "What does 多少 mean?", type: "multiple_choice", correct: "How much / How many", options: ["How old", "How big", "How much / How many", "How far"] },
    { question: "How do you ask 'How much is it?'", type: "multiple_choice", correct: "多少钱？", options: ["几个钱？", "多少块？", "多少钱？", "几多钱？"] },
    { question: "What is 钱?", type: "multiple_choice", correct: "Money", options: ["Price", "Money", "Coin", "Bill"] },
    { question: "What does 贵 mean?", type: "multiple_choice", correct: "Expensive", options: ["Cheap", "Big", "Expensive", "Small"] },
    { question: "What does 便宜 mean?", type: "multiple_choice", correct: "Cheap / Inexpensive", options: ["Expensive", "Cheap / Inexpensive", "Reasonable", "Free"] },
    { question: "What is 块 (kuài)?", type: "multiple_choice", correct: "Chinese yuan (colloquial)", options: ["Cent", "Dollar", "Chinese yuan (colloquial)", "Ten yuan"] },
    { question: "What is the measure word for books?", type: "multiple_choice", correct: "本", options: ["个", "杯", "本", "张"] },
    { question: "How do you say 'this book'?", type: "multiple_choice", correct: "这本书", options: ["这书", "这个书", "这本书", "这本的书"] },
    { question: "What does 东西 mean?", type: "multiple_choice", correct: "Thing / Item / Stuff", options: ["East and west", "Things / Items / Stuff", "Direction", "Place"] },
    { question: "How do you say 'I want to buy things.'?", type: "multiple_choice", correct: "我想买东西。", options: ["我要买东西。", "我想买东西。", "Both A and B", "Neither"] },
    { question: "What is 书?", type: "multiple_choice", correct: "Book", options: ["Notebook", "Book", "Magazine", "Newspaper"] },
    { question: "这本书多少钱？means:", type: "multiple_choice", correct: "How much is this book?", options: ["Where is this book?", "Whose book is this?", "How much is this book?", "Do you want this book?"] },
    { question: "How do you say 'This is too expensive.'?", type: "multiple_choice", correct: "这太贵了。", options: ["这很贵。", "这太贵。", "这太贵了。", "这太了贵。"] },
    { question: "What does 少 mean?", type: "multiple_choice", correct: "Few / Little", options: ["Many", "Big", "Few / Little", "Small"] },
    { question: "What does 多 mean?", type: "multiple_choice", correct: "Many / Much", options: ["Few", "Many / Much", "Big", "All"] },
    { question: "How do you say 'a little cheaper'?", type: "multiple_choice", correct: "便宜一点", options: ["一点便宜", "便宜一些", "便宜一点", "Both B and C"] },
    { question: "What is 元?", type: "multiple_choice", correct: "Yuan (formal written form)", options: ["Cent", "Yuan (formal written form)", "Dollar", "Ten yuan"] },
    { question: "Translate: '50 yuan'", type: "multiple_choice", correct: "五十块钱", options: ["五十块钱", "五十元钱", "五十钱块", "Both A and B"] },
    { question: "How do you say 'I want to buy this book.'?", type: "multiple_choice", correct: "我想买这本书。", options: ["我买这本书想。", "我想买这本书。", "我这本书想买。", "这本书我买想。"] },
    { question: "What does 件 mean as a measure word?", type: "multiple_choice", correct: "Piece/item (for clothes, matters)", options: ["Item (for books)", "Cup (for drinks)", "Piece/item (for clothes, matters)", "Flat item (for paper)"] },
    { question: "Translate: 'expensive things'", type: "multiple_choice", correct: "贵东西", options: ["很东西", "贵东西", "东西贵", "贵的东西"] },
    { question: "How do you say 'three books'?", type: "multiple_choice", correct: "三本书", options: ["三书本", "书三本", "三本书", "三个书"] },
    { question: "What does 一点 mean after an adjective?", type: "multiple_choice", correct: "A little (more/less)", options: ["Very", "A little (more/less)", "Too much", "A lot"] },
    { question: "Choose correct: 'This is cheap.'", type: "multiple_choice", correct: "这个很便宜。", options: ["这个是便宜。", "这个便宜很。", "这个很便宜。", "很便宜这个。"] }
  ],

  7: [
    { question: "What does 在 mean in '你在哪儿？'", type: "multiple_choice", correct: "At / Located at", options: ["Going to", "Coming from", "At / Located at", "In the future at"] },
    { question: "What does 哪儿 mean?", type: "multiple_choice", correct: "Where", options: ["Here", "There", "Where", "Which place"] },
    { question: "这儿 means:", type: "multiple_choice", correct: "Here", options: ["There", "Here", "Where", "Nearby"] },
    { question: "那儿 means:", type: "multiple_choice", correct: "There", options: ["Here", "There", "Where", "That place"] },
    { question: "What does 学校 mean?", type: "multiple_choice", correct: "School", options: ["Hospital", "School", "Store", "Library"] },
    { question: "What does 医院 mean?", type: "multiple_choice", correct: "Hospital", options: ["School", "Pharmacy", "Hospital", "Clinic"] },
    { question: "What does 商店 mean?", type: "multiple_choice", correct: "Shop / Store", options: ["Restaurant", "School", "Shop / Store", "Market"] },
    { question: "How do you ask 'Where is the school?'", type: "multiple_choice", correct: "学校在哪儿？", options: ["学校哪儿在？", "在哪儿学校？", "学校在哪儿？", "哪儿是学校？"] },
    { question: "What does 上 mean as a position word?", type: "multiple_choice", correct: "On / Above / On top", options: ["Below", "In front", "On / Above / On top", "Behind"] },
    { question: "What does 下 mean as a position word?", type: "multiple_choice", correct: "Under / Below", options: ["On top", "Under / Below", "In front", "Behind"] },
    { question: "What does 里 mean?", type: "multiple_choice", correct: "Inside / In", options: ["Outside", "In front", "Inside / In", "Behind"] },
    { question: "What does 前 mean?", type: "multiple_choice", correct: "In front / Before", options: ["Behind", "In front / Before", "Left", "Right"] },
    { question: "What does 后 mean?", type: "multiple_choice", correct: "Behind / After", options: ["In front", "Left", "Behind / After", "Right"] },
    { question: "How do you say 'The cat is under the table.'?", type: "multiple_choice", correct: "猫在桌子下。", options: ["猫在桌子上。", "猫在桌子下。", "猫下桌子。", "桌子下猫在。"] },
    { question: "你在哪儿？means:", type: "multiple_choice", correct: "Where are you?", options: ["Where are you going?", "Where are you from?", "Where are you?", "Where do you work?"] },
    { question: "How do you say 'I am at home.'?", type: "multiple_choice", correct: "我在家。", options: ["我是家。", "我有家。", "我在家。", "家在我。"] },
    { question: "What does 旁边 mean?", type: "multiple_choice", correct: "Next to / Beside", options: ["In front", "Behind", "Next to / Beside", "Above"] },
    { question: "医院在哪儿？means:", type: "multiple_choice", correct: "Where is the hospital?", options: ["Is this a hospital?", "Where is the hospital?", "Go to the hospital", "How far is the hospital?"] },
    { question: "How do you say 'in the school'?", type: "multiple_choice", correct: "在学校里", options: ["学校里在", "在学校", "在学校里", "Both B and C"] },
    { question: "What does 外 mean?", type: "multiple_choice", correct: "Outside / Out", options: ["Inside", "Outside / Out", "Front", "Back"] },
    { question: "How do you say 'The hospital is in front.'?", type: "multiple_choice", correct: "医院在前面。", options: ["医院前面在。", "前面在医院。", "医院在前面。", "在前面医院。"] },
    { question: "Which is the correct way to describe location?", type: "multiple_choice", correct: "书在桌子上。", options: ["上桌子书在。", "书桌子在上。", "书在桌子上。", "在上书桌子。"] },
    { question: "What does 中间 mean?", type: "multiple_choice", correct: "Middle / Center", options: ["Side", "Corner", "Middle / Center", "Edge"] },
    { question: "Translate: 'The shop is next to the school.'", type: "multiple_choice", correct: "商店在学校旁边。", options: ["商店旁边学校在。", "商店在学校旁边。", "学校在商店旁边。", "旁边商店在学校。"] },
    { question: "What formula describes location in Chinese?", type: "multiple_choice", correct: "Subject + 在 + Location", options: ["Location + 在 + Subject", "Subject + 是 + Location", "Subject + 在 + Location", "Location + Subject + 在"] }
  ],

  8: [
    { question: "What does 做 mean?", type: "multiple_choice", correct: "To do / To make", options: ["To go", "To have", "To do / To make", "To work"] },
    { question: "What does 看 mean?", type: "multiple_choice", correct: "To look / Watch / Read", options: ["To listen", "To speak", "To look / Watch / Read", "To write"] },
    { question: "What does 看电视 mean?", type: "multiple_choice", correct: "Watch TV", options: ["Fix the TV", "Watch TV", "Buy a TV", "Turn on the TV"] },
    { question: "What does 看电影 mean?", type: "multiple_choice", correct: "Watch a movie", options: ["Make a movie", "Watch a movie", "Buy a movie ticket", "Talk about a movie"] },
    { question: "What does 读 mean?", type: "multiple_choice", correct: "To read (aloud)", options: ["To write", "To listen", "To read (aloud)", "To study"] },
    { question: "What does 写 mean?", type: "multiple_choice", correct: "To write", options: ["To read", "To draw", "To write", "To paint"] },
    { question: "What does 去 mean?", type: "multiple_choice", correct: "To go", options: ["To come", "To go", "To leave", "To stay"] },
    { question: "What does 来 mean?", type: "multiple_choice", correct: "To come", options: ["To go", "To leave", "To come", "To arrive"] },
    { question: "What does 回 mean?", type: "multiple_choice", correct: "To return / Go back", options: ["To go forward", "To turn around", "To return / Go back", "To enter"] },
    { question: "How do you say '他在看书。' in English?", type: "multiple_choice", correct: "He is reading a book.", options: ["He reads a book.", "He read a book.", "He is reading a book.", "He will read a book."] },
    { question: "What does 在 + verb indicate?", type: "multiple_choice", correct: "Ongoing action right now", options: ["Completed action", "Future plan", "Ongoing action right now", "Location"] },
    { question: "How do you say 'She is writing characters.'?", type: "multiple_choice", correct: "她在写汉字。", options: ["她写汉字了。", "她在写汉字。", "她写了汉字。", "她将写汉字。"] },
    { question: "What does 电视 mean?", type: "multiple_choice", correct: "Television", options: ["Computer", "Phone", "Television", "Radio"] },
    { question: "What does 电影 mean?", type: "multiple_choice", correct: "Movie / Film", options: ["TV show", "Movie / Film", "Music", "Book"] },
    { question: "What does 汉字 mean?", type: "multiple_choice", correct: "Chinese characters", options: ["Chinese people", "Chinese language", "Chinese characters", "Chinese culture"] },
    { question: "How do you say 'I go to work.'?", type: "multiple_choice", correct: "我去工作。", options: ["我在工作。", "我做工作。", "我去工作。", "All are correct"] },
    { question: "What does 看见 mean?", type: "multiple_choice", correct: "To see / Catch sight of", options: ["To look at carefully", "To see / Catch sight of", "To watch TV", "To notice"] },
    { question: "How do you say 'Let's go home.'?", type: "multiple_choice", correct: "我们回家吧。", options: ["我们去家吧。", "我们回家吧。", "我们来家吧。", "我们家回吧。"] },
    { question: "What is 书?", type: "multiple_choice", correct: "Book", options: ["Notebook", "Book", "Dictionary", "Magazine"] },
    { question: "What does 读书 vs 看书 difference?", type: "multiple_choice", correct: "读书 = read aloud; 看书 = read silently", options: ["They are the same", "读书 = read aloud; 看书 = read silently", "看书 = read aloud; 读书 = read silently", "Only 看书 is correct"] },
    { question: "Translate: 'What are you doing?'", type: "multiple_choice", correct: "你在做什么？", options: ["你做什么了？", "你做什么？", "你在做什么？", "Both B and C"] },
    { question: "How do you say 'Come to my home.'?", type: "multiple_choice", correct: "来我家。", options: ["去我家。", "在我家。", "来我家。", "到我家。"] },
    { question: "What does 写字 mean?", type: "multiple_choice", correct: "Write characters / Write", options: ["Type on computer", "Write characters / Write", "Read characters", "Draw pictures"] },
    { question: "她在做什么？She is watching TV. Which is correct?", type: "multiple_choice", correct: "她在看电视。", options: ["她看电视了。", "她有看电视。", "她在看电视。", "她是看电视。"] },
    { question: "How do you say 'I am going to school.'?", type: "multiple_choice", correct: "我去学校。", options: ["我在学校去。", "我去学校。", "我来学校。", "我是学校去。"] }
  ],

  9: [
    { question: "What does 朋友 mean?", type: "multiple_choice", correct: "Friend", options: ["Classmate", "Teacher", "Friend", "Family"] },
    { question: "What does 同学 mean?", type: "multiple_choice", correct: "Classmate", options: ["Friend", "Classmate", "Colleague", "Teammate"] },
    { question: "What does 认识 mean?", type: "multiple_choice", correct: "To know / To meet (someone)", options: ["To study", "To see", "To know / To meet (someone)", "To remember"] },
    { question: "What does 高兴 mean?", type: "multiple_choice", correct: "Happy / Glad", options: ["Sad", "Angry", "Happy / Glad", "Tired"] },
    { question: "What does 对不起 mean?", type: "multiple_choice", correct: "Sorry / Excuse me", options: ["You're welcome", "Thank you", "Sorry / Excuse me", "Goodbye"] },
    { question: "What does 不客气 mean?", type: "multiple_choice", correct: "You're welcome", options: ["Sorry", "You're welcome", "Thank you", "It's okay"] },
    { question: "What does 汉语 mean?", type: "multiple_choice", correct: "Chinese language (Mandarin)", options: ["China", "Chinese people", "Chinese language (Mandarin)", "Chinese culture"] },
    { question: "What does 说 mean?", type: "multiple_choice", correct: "To speak / To say", options: ["To listen", "To write", "To speak / To say", "To read"] },
    { question: "What does 会 express?", type: "multiple_choice", correct: "Learned skill / ability", options: ["Physical ability", "Permission", "Learned skill / ability", "Desire"] },
    { question: "How do you say 'Nice to meet you!'?", type: "multiple_choice", correct: "认识你很高兴！", options: ["你好高兴！", "认识你很好！", "认识你很高兴！", "见你很高兴！"] },
    { question: "What does 中国 mean?", type: "multiple_choice", correct: "China", options: ["Chinese language", "China", "Chinese people", "Center"] },
    { question: "What does 我们 mean?", type: "multiple_choice", correct: "We / Us", options: ["I/Me", "You all", "We / Us", "They"] },
    { question: "How do you say 'Can you speak Chinese?'", type: "multiple_choice", correct: "你会说汉语吗？", options: ["你能说汉语吗？", "你会说汉语吗？", "你说汉语吗？", "你学汉语吗？"] },
    { question: "What is the response to 对不起?", type: "multiple_choice", correct: "没关系", options: ["不客气", "谢谢", "没关系", "再见"] },
    { question: "What does 先生 mean?", type: "multiple_choice", correct: "Mr. / Sir / Husband", options: ["Miss / Ms.", "Mr. / Sir / Husband", "Teacher", "Friend"] },
    { question: "How do you make pronouns plural in Chinese?", type: "multiple_choice", correct: "Add 们: 我→我们, 你→你们", options: ["Add 多: 我多", "Add 们: 我→我们, 你→你们", "Add 们 only for you", "Pronouns can't be plural"] },
    { question: "你们好！means:", type: "multiple_choice", correct: "Hello everyone!", options: ["Are you all good?", "Hello everyone!", "How are you all?", "You all are good."] },
    { question: "Translate: 'We are friends.'", type: "multiple_choice", correct: "我们是朋友。", options: ["我们有朋友。", "我们的朋友。", "我们是朋友。", "朋友是我们。"] },
    { question: "What is the difference between 会 and 能?", type: "multiple_choice", correct: "会 = learned skill; 能 = situational ability", options: ["They mean exactly the same", "会 = situational; 能 = learned skill", "会 = learned skill; 能 = situational ability", "Neither can be used for language"] },
    { question: "How do you say 'Let's study together!'?", type: "multiple_choice", correct: "我们一起学习！", options: ["我们学习一起！", "一起我们学习！", "我们一起学习！", "我们学习！"] },
    { question: "Translate: 'I can speak a little Chinese.'", type: "multiple_choice", correct: "我会说一点汉语。", options: ["我能说一点汉语。", "我会说一点汉语。", "我说一点汉语。", "Both A and B are correct"] },
    { question: "What is 他们?", type: "multiple_choice", correct: "They (male or mixed group)", options: ["She and he", "They (male or mixed group)", "You all", "We"] },
    { question: "How do you say 'I'm glad too.'?", type: "multiple_choice", correct: "我也很高兴！", options: ["我很高兴也！", "我高兴也！", "也我很高兴！", "我也很高兴！"] },
    { question: "好朋友 means:", type: "multiple_choice", correct: "Good friend / Best friend", options: ["Good student", "New friend", "Good friend / Best friend", "Old friend"] },
    { question: "Translate: 'We are classmates.'", type: "multiple_choice", correct: "我们是同学。", options: ["我们有同学。", "我们是朋友。", "我们是同学。", "同学是我们。"] }
  ],

  10: [
    { question: "What does 天气 mean?", type: "multiple_choice", correct: "Weather", options: ["Sky", "Air", "Weather", "Climate"] },
    { question: "What does 热 mean?", type: "multiple_choice", correct: "Hot", options: ["Cold", "Warm", "Hot", "Cool"] },
    { question: "What does 冷 mean?", type: "multiple_choice", correct: "Cold", options: ["Hot", "Cool", "Cold", "Warm"] },
    { question: "What does 下雨 mean?", type: "multiple_choice", correct: "To rain / Raining", options: ["To snow", "To rain / Raining", "Windy", "Cloudy"] },
    { question: "What does 太 mean?", type: "multiple_choice", correct: "Too / Extremely", options: ["Very", "A little", "Too / Extremely", "Also"] },
    { question: "Complete the pattern: 太 + adjective + ___", type: "multiple_choice", correct: "了", options: ["吗", "了", "的", "呢"] },
    { question: "What does 怎么样 ask?", type: "multiple_choice", correct: "How is it / What's it like", options: ["How much", "Where", "How is it / What's it like", "When"] },
    { question: "How do you say 'How's the weather?'", type: "multiple_choice", correct: "天气怎么样？", options: ["今天怎么样？", "天气什么样？", "天气怎么样？", "天气是怎么？"] },
    { question: "What does 大 mean?", type: "multiple_choice", correct: "Big / Large", options: ["Small", "Tall", "Big / Large", "Wide"] },
    { question: "What does 小 mean?", type: "multiple_choice", correct: "Small / Little", options: ["Big", "Thin", "Small / Little", "Short"] },
    { question: "What does 多 mean?", type: "multiple_choice", correct: "Many / Much", options: ["Few", "Some", "Many / Much", "All"] },
    { question: "What does 少 mean?", type: "multiple_choice", correct: "Few / Little / Less", options: ["Many", "Some", "Few / Little / Less", "None"] },
    { question: "What does 和 connect?", type: "multiple_choice", correct: "Nouns and pronouns only", options: ["Verbs", "Sentences", "Nouns and pronouns only", "Adjectives only"] },
    { question: "Translate: '你和我' ", type: "multiple_choice", correct: "You and I", options: ["You or me", "You with me", "You and I", "You like me"] },
    { question: "What does 一些 mean?", type: "multiple_choice", correct: "Some / A few", options: ["One", "Many", "Some / A few", "All"] },
    { question: "How do you say 'It's too hot!'?", type: "multiple_choice", correct: "太热了！", options: ["很热了！", "太热！", "太热了！", "热太了！"] },
    { question: "Translate: 'The weather is good today.'", type: "multiple_choice", correct: "今天天气很好。", options: ["今天很天气好。", "天气今天很好。", "今天天气很好。", "很好今天天气。"] },
    { question: "How do you say 'a little more'?", type: "multiple_choice", correct: "多一点", options: ["一点多", "多点", "多一点", "一些多"] },
    { question: "How do you say 'a little less'?", type: "multiple_choice", correct: "少一点", options: ["一点少", "少点", "少一点", "一些少"] },
    { question: "What does 下雨了 mean vs 下雨?", type: "multiple_choice", correct: "下雨了 = it started raining (new situation)", options: ["They mean the same", "下雨了 = it started raining (new situation)", "下雨 = it started raining", "了 makes it past tense"] },
    { question: "Translate: 'It's raining heavily today.'", type: "multiple_choice", correct: "今天下大雨。", options: ["今天大下雨。", "今天下大雨。", "下大雨今天。", "今天大雨下。"] },
    { question: "茶和咖啡 means:", type: "multiple_choice", correct: "Tea and coffee", options: ["Tea or coffee", "Tea with coffee", "Tea and coffee", "Tea like coffee"] },
    { question: "Which sentence is grammatically correct?", type: "multiple_choice", correct: "今天天气太冷了。", options: ["今天太天气冷了。", "天气冷太了今天。", "今天天气太冷了。", "太冷了今天天气。"] },
    { question: "How do you ask 'How about tomorrow?'", type: "multiple_choice", correct: "明天呢？", options: ["明天怎么？", "明天是怎样？", "明天呢？", "明天如何？"] },
    { question: "Translate: 'Have some hot tea.'", type: "multiple_choice", correct: "喝一些热茶吧。", options: ["吃一些热茶吧。", "喝一些热茶吧。", "一些热茶喝吧。", "喝热茶一些。"] }
  ],

  11: [
    { question: "What does 现在 mean?", type: "multiple_choice", correct: "Now", options: ["Before", "After", "Now", "Soon"] },
    { question: "How do you ask 'What time is it?'", type: "multiple_choice", correct: "现在几点？", options: ["今天几点？", "现在几时？", "现在几点？", "今天什么时间？"] },
    { question: "What does 分钟 mean?", type: "multiple_choice", correct: "Minute (duration)", options: ["Second", "Hour", "Minute (duration)", "Moment"] },
    { question: "What does 中午 mean?", type: "multiple_choice", correct: "Noon / Midday", options: ["Morning", "Afternoon", "Noon / Midday", "Evening"] },
    { question: "What does 时候 mean?", type: "multiple_choice", correct: "Time / When / Moment", options: ["Clock", "Hour", "Time / When / Moment", "Minutes"] },
    { question: "What does 星期 mean?", type: "multiple_choice", correct: "Week / Day of the week", options: ["Month", "Year", "Week / Day of the week", "Weekend"] },
    { question: "How do you say 'Monday'?", type: "multiple_choice", correct: "星期一", options: ["星期日", "星期一", "星期七", "周一"] },
    { question: "How do you say 'Sunday'?", type: "multiple_choice", correct: "星期天 / 星期日", options: ["星期七", "星期六", "星期天 / 星期日", "星期零"] },
    { question: "How do you say '3:30'?", type: "multiple_choice", correct: "三点半", options: ["三点三十分", "三点半", "Both are correct", "三时半"] },
    { question: "How do you say '9:15'?", type: "multiple_choice", correct: "九点十五分", options: ["九点一五分", "九时十五分", "九点十五分", "十五分九点"] },
    { question: "What does 打电话 mean?", type: "multiple_choice", correct: "To make a phone call", options: ["To answer a phone", "To make a phone call", "To hang up", "To text"] },
    { question: "What does 喂 mean when answering the phone?", type: "multiple_choice", correct: "Hello (on the phone)", options: ["Goodbye", "I'm busy", "Hello (on the phone)", "Who is this?"] },
    { question: "What does 听 mean?", type: "multiple_choice", correct: "To listen / To hear", options: ["To speak", "To see", "To listen / To hear", "To understand"] },
    { question: "What does 请问 mean?", type: "multiple_choice", correct: "Excuse me / May I ask", options: ["Please wait", "Thank you", "Excuse me / May I ask", "You're welcome"] },
    { question: "How do you ask 'What day is today?'", type: "multiple_choice", correct: "今天星期几？", options: ["今天是几号？", "今天几点？", "今天星期几？", "几天了？"] },
    { question: "What does 什么时候 ask?", type: "multiple_choice", correct: "When (what time/moment)", options: ["What kind of time", "When (what time/moment)", "How long", "For how long"] },
    { question: "Translate: 'I'll come in 10 minutes.'", type: "multiple_choice", correct: "我十分钟后来。", options: ["我来十分钟后。", "十分钟我后来。", "我十分钟后来。", "我后十分钟来。"] },
    { question: "How do you say 'When are you coming?'", type: "multiple_choice", correct: "你什么时候来？", options: ["你来什么时候？", "什么时候你来？", "你什么时候来？", "你时候什么来？"] },
    { question: "Translate: '下午两点半'", type: "multiple_choice", correct: "2:30 PM", options: ["2:30 AM", "2:50 PM", "2:30 PM", "2:15 PM"] },
    { question: "What is 今年?", type: "multiple_choice", correct: "This year", options: ["Last year", "Next year", "This year", "Many years"] },
    { question: "What is 明年?", type: "multiple_choice", correct: "Next year", options: ["Last year", "Next year", "This year", "The coming year"] },
    { question: "How do you say 'It's 12:00 noon.'?", type: "multiple_choice", correct: "现在中午十二点。", options: ["现在十二点中午。", "中午现在十二点。", "现在中午十二点。", "十二点中午现在。"] },
    { question: "Star Week: 星期三 means:", type: "multiple_choice", correct: "Wednesday", options: ["Tuesday", "Wednesday", "Thursday", "Friday"] },
    { question: "How do you say 'I heard that…'?", type: "multiple_choice", correct: "听说…", options: ["听到…", "说听…", "听说…", "我听到说…"] },
    { question: "Translate: 'Please call me.'", type: "multiple_choice", correct: "请打电话给我。", options: ["请听电话给我。", "打电话请我。", "请打电话给我。", "给我打请电话。"] }
  ],

  12: [
    { question: "What does 能 mean?", type: "multiple_choice", correct: "Can / Be able to (situationally)", options: ["Want to", "Know how to", "Can / Be able to (situationally)", "Must"] },
    { question: "What is the key difference between 能 and 会?", type: "multiple_choice", correct: "能 = situational ability; 会 = learned skill", options: ["They are the same", "能 = learned skill; 会 = situational", "能 = situational ability; 会 = learned skill", "Neither can be used for language"] },
    { question: "What does 漂亮 mean?", type: "multiple_choice", correct: "Beautiful / Pretty", options: ["Ugly", "Big", "Beautiful / Pretty", "Interesting"] },
    { question: "What does 学习 mean?", type: "multiple_choice", correct: "To study / To learn", options: ["To teach", "To study / To learn", "To read", "To work"] },
    { question: "What does 学生 mean?", type: "multiple_choice", correct: "Student", options: ["Teacher", "Student", "Worker", "Doctor"] },
    { question: "What is 水果?", type: "multiple_choice", correct: "Fruit", options: ["Vegetable", "Juice", "Fruit", "Snack"] },
    { question: "What does 睡觉 mean?", type: "multiple_choice", correct: "To sleep", options: ["To wake up", "To rest", "To sleep", "To lie down"] },
    { question: "What is 猫?", type: "multiple_choice", correct: "Cat", options: ["Dog", "Cat", "Bird", "Fish"] },
    { question: "What is 狗?", type: "multiple_choice", correct: "Dog", options: ["Cat", "Horse", "Dog", "Rabbit"] },
    { question: "What does 都 mean?", type: "multiple_choice", correct: "All / Both", options: ["Some", "Only", "All / Both", "Either"] },
    { question: "Where does 都 go in a sentence?", type: "multiple_choice", correct: "Before the verb", options: ["After the subject, before verb", "After the verb", "Before the subject", "Before the verb"] },
    { question: "What does 怎么 ask?", type: "multiple_choice", correct: "How (method/way)", options: ["How (description)", "When", "How (method/way)", "Why"] },
    { question: "Translate: 'They are all students.'", type: "multiple_choice", correct: "他们都是学生。", options: ["都他们是学生。", "他们是都学生。", "他们都是学生。", "都学生他们是。"] },
    { question: "How do you ask 'Can you come tomorrow?'", type: "multiple_choice", correct: "你明天能来吗？", options: ["你明天会来吗？", "你明天能来吗？", "你明天可以来吗？", "Both B and C"] },
    { question: "How do you say 'I have a cat and a dog.'?", type: "multiple_choice", correct: "我有一只猫和一只狗。", options: ["我有一个猫和一个狗。", "我有一只猫和一只狗。", "我有猫和狗一只。", "一只猫和一只狗我有。"] },
    { question: "What is the measure word for animals (cats, dogs)?", type: "multiple_choice", correct: "只", options: ["个", "条", "只", "头"] },
    { question: "What does 小姐 mean?", type: "multiple_choice", correct: "Miss / Ms. / Young woman", options: ["Old woman", "Miss / Ms. / Young woman", "Mrs.", "Little sister"] },
    { question: "What does 女人 mean?", type: "multiple_choice", correct: "Woman", options: ["Girl", "Woman", "Lady", "Female student"] },
    { question: "Translate: 'How do you study Chinese?'", type: "multiple_choice", correct: "你怎么学习汉语？", options: ["你学习汉语怎么？", "怎么你学习汉语？", "你怎么学习汉语？", "你汉语怎么学习？"] },
    { question: "怎么 vs 怎么样: which asks for a description?", type: "multiple_choice", correct: "怎么样 (how is it / what's it like)", options: ["怎么 (how)", "怎么样 (how is it / what's it like)", "Both ask for description", "Neither"] },
    { question: "How do you say 'Both are very good.'?", type: "multiple_choice", correct: "都很好。", options: ["都是好。", "两个很好。", "都很好。", "很都好。"] },
    { question: "Translate: 'She is very beautiful.'", type: "multiple_choice", correct: "她很漂亮。", options: ["她是漂亮。", "她很漂亮。", "漂亮她很。", "她漂亮很。"] },
    { question: "How do you say 'I eat fruit every day.'?", type: "multiple_choice", correct: "我每天吃水果。", options: ["我吃水果每天。", "每天我吃水果。", "我每天吃水果。", "Both B and C"] },
    { question: "能不能 means:", type: "multiple_choice", correct: "Can or cannot? / Is it possible?", options: ["Definitely can", "Definitely cannot", "Can or cannot? / Is it possible?", "Want or don't want?"] },
    { question: "Translate: 'We are all friends.'", type: "multiple_choice", correct: "我们都是朋友。", options: ["我们是都朋友。", "都我们是朋友。", "我们都是朋友。", "朋友我们都是。"] }
  ],

  13: [
    { question: "What does 电脑 mean?", type: "multiple_choice", correct: "Computer", options: ["Television", "Phone", "Computer", "Tablet"] },
    { question: "What does 椅子 mean?", type: "multiple_choice", correct: "Chair", options: ["Table", "Sofa", "Chair", "Bench"] },
    { question: "What does 桌子 mean?", type: "multiple_choice", correct: "Table / Desk", options: ["Chair", "Shelf", "Table / Desk", "Cabinet"] },
    { question: "What does 住 mean?", type: "multiple_choice", correct: "To live / To reside", options: ["To stay overnight", "To visit", "To live / To reside", "To move"] },
    { question: "What does 饭馆 mean?", type: "multiple_choice", correct: "Restaurant", options: ["Cafeteria", "Supermarket", "Restaurant", "Hotel"] },
    { question: "What is 杯子?", type: "multiple_choice", correct: "Cup / Glass (the object)", options: ["Cup of tea", "Cupboard", "Cup / Glass (the object)", "Plate"] },
    { question: "What does 这 mean?", type: "multiple_choice", correct: "This", options: ["That", "Which", "This", "Here"] },
    { question: "What does 那 mean?", type: "multiple_choice", correct: "That", options: ["This", "Which", "That", "There"] },
    { question: "What does 哪 mean?", type: "multiple_choice", correct: "Which (question word)", options: ["This", "That", "Here", "Which (question word)"] },
    { question: "这儿 and 那儿 mean:", type: "multiple_choice", correct: "Here and there", options: ["This and that", "Here and where", "Here and there", "Near and far"] },
    { question: "What does 开 mean in 开电脑?", type: "multiple_choice", correct: "Turn on", options: ["Open physically", "Operate", "Turn on", "Start programs"] },
    { question: "How do you ask 'Where do you live?'", type: "multiple_choice", correct: "你住在哪儿？", options: ["你在哪儿住？", "你住哪儿？", "你住在哪儿？", "All are correct"] },
    { question: "How do you say 'The computer is on the desk.'?", type: "multiple_choice", correct: "电脑在桌子上。", options: ["电脑桌子上在。", "在桌子上电脑。", "电脑在桌子上。", "桌子上有电脑在。"] },
    { question: "这是什么？means:", type: "multiple_choice", correct: "What is this?", options: ["Is this good?", "What is this?", "Where is this?", "Whose is this?"] },
    { question: "How do you say 'that restaurant'?", type: "multiple_choice", correct: "那个饭馆", options: ["这个饭馆", "哪个饭馆", "那个饭馆", "那饭馆"] },
    { question: "How do you ask 'Which one is good?'", type: "multiple_choice", correct: "哪个好？", options: ["那个好？", "这个好？", "哪个好？", "什么好？"] },
    { question: "What does 住在 + place mean?", type: "multiple_choice", correct: "Live in/at [place]", options: ["Stay at [place]", "Work at [place]", "Live in/at [place]", "Visit [place]"] },
    { question: "Translate: 'I live next to the school.'", type: "multiple_choice", correct: "我住在学校旁边。", options: ["我住旁边学校。", "我在学校住旁边。", "我住在学校旁边。", "学校旁边我住在。"] },
    { question: "How do you say 'Let's go to that restaurant.'?", type: "multiple_choice", correct: "我们去那个饭馆吧。", options: ["我们去这个饭馆吧。", "我们去哪个饭馆吧？", "我们去那个饭馆吧。", "我们那个饭馆去吧。"] },
    { question: "请坐！means:", type: "multiple_choice", correct: "Please sit down!", options: ["Can I sit?", "Please stand up!", "Please sit down!", "Are you sitting?"] },
    { question: "What does 开门 mean?", type: "multiple_choice", correct: "Open the door", options: ["Close the door", "Open the door", "Lock the door", "Knock on the door"] },
    { question: "How do you say 'turn on the computer'?", type: "multiple_choice", correct: "开电脑", options: ["关电脑", "开电视", "开电脑", "用电脑"] },
    { question: "Which is the correct 这/那/哪 for a question?", type: "multiple_choice", correct: "哪", options: ["这", "那", "哪", "Any of them"] },
    { question: "Translate: 'Here or there?'", type: "multiple_choice", correct: "在这儿还是那儿？", options: ["在哪儿？", "这儿吗？", "在这儿还是那儿？", "这儿那儿？"] },
    { question: "What's the difference between 杯 and 杯子?", type: "multiple_choice", correct: "杯 = measure word (a cup of); 杯子 = the cup object", options: ["They are the same", "杯子 = measure word; 杯 = the object", "杯 = measure word (a cup of); 杯子 = the cup object", "Both only mean the object"] }
  ],

  14: [
    { question: "What does 了 after a verb indicate?", type: "multiple_choice", correct: "Completed action", options: ["Future action", "Ongoing action", "Completed action", "Desired action"] },
    { question: "What does 衣服 mean?", type: "multiple_choice", correct: "Clothes / Clothing", options: ["Shoes", "Bag", "Clothes / Clothing", "Hat"] },
    { question: "What does 女儿 mean?", type: "multiple_choice", correct: "Daughter", options: ["Son", "Girl", "Daughter", "Sister"] },
    { question: "What does 儿子 mean?", type: "multiple_choice", correct: "Son", options: ["Daughter", "Boy", "Son", "Brother"] },
    { question: "What does 医生 mean?", type: "multiple_choice", correct: "Doctor", options: ["Nurse", "Hospital", "Doctor", "Patient"] },
    { question: "What does 工作 mean?", type: "multiple_choice", correct: "Work / Job / To work", options: ["School", "Study", "Work / Job / To work", "Task"] },
    { question: "How do you say 'I ate rice.' (completed)?", type: "multiple_choice", correct: "我吃了米饭。", options: ["我吃米饭了。", "我吃了米饭。", "Both are correct", "我有吃米饭。"] },
    { question: "How do you negate a completed action?", type: "multiple_choice", correct: "Use 没有 + verb (remove 了)", options: ["Use 不 + verb + 了", "Use 没有 + verb (remove 了)", "Add 不 before 了", "Use 没 + 了 + verb"] },
    { question: "How do you say 'I haven't eaten yet.'?", type: "multiple_choice", correct: "我还没吃。", options: ["我没吃了。", "我不吃了。", "我还没吃。", "我还不吃。"] },
    { question: "What does 以前 mean?", type: "multiple_choice", correct: "Before / Previously", options: ["After / Later", "Now", "Before / Previously", "During"] },
    { question: "What does 以后 mean?", type: "multiple_choice", correct: "After / Later / In the future", options: ["Before", "Now", "During", "After / Later / In the future"] },
    { question: "What does 又 mean?", type: "multiple_choice", correct: "Again / Once more", options: ["Also", "Still", "Again / Once more", "Already"] },
    { question: "How do you say 'She bought clothes again.'?", type: "multiple_choice", correct: "她又买了衣服。", options: ["她买了又衣服。", "她又买了衣服。", "又她买了衣服。", "她买衣服又了。"] },
    { question: "What does 还 in 还没 mean?", type: "multiple_choice", correct: "Still / Yet", options: ["Also", "Already", "Still / Yet", "Even"] },
    { question: "What does 自己 mean?", type: "multiple_choice", correct: "Oneself / Yourself", options: ["Alone", "Together", "Oneself / Yourself", "By someone else"] },
    { question: "Translate: 'My son is a doctor.'", type: "multiple_choice", correct: "我儿子是医生。", options: ["我的儿子医生。", "我儿子有医生。", "我儿子是医生。", "儿子我是医生。"] },
    { question: "How do you say 'Did you eat?' (using 了)?", type: "multiple_choice", correct: "你吃了吗？", options: ["你吃吗了？", "你了吃吗？", "你吃了吗？", "吃了你吗？"] },
    { question: "Translate: 'I was a student before.'", type: "multiple_choice", correct: "我以前是学生。", options: ["我是以前学生。", "以前我是学生。", "我以前是学生。", "Both B and C"] },
    { question: "What does 男人 mean?", type: "multiple_choice", correct: "Man", options: ["Boy", "Man", "Husband", "Male friend"] },
    { question: "How do you say 'What work does he do?'", type: "multiple_choice", correct: "他做什么工作？", options: ["他工作什么做？", "什么他工作做？", "他做什么工作？", "他做工作什么？"] },
    { question: "以前 and 以后 come ___ the verb:", type: "multiple_choice", correct: "Before the verb clause", options: ["After the verb clause", "After the object", "Before the verb clause", "Between subject and verb"] },
    { question: "我还没吃。vs 我没吃了。— which is correct?", type: "multiple_choice", correct: "我还没吃。 (correct)", options: ["我没吃了。 (correct)", "我还没吃。 (correct)", "Both are correct", "Neither is correct"] },
    { question: "Translate: 'I want to open my own restaurant in the future.'", type: "multiple_choice", correct: "我以后想自己开一个饭馆。", options: ["以后我开自己饭馆想。", "我以后想自己开一个饭馆。", "自己我以后开饭馆想。", "我想自己以后开饭馆。"] },
    { question: "What does 人 mean?", type: "multiple_choice", correct: "Person / People", options: ["Man", "Woman", "Person / People", "Human body"] },
    { question: "How do you say 'They have both started working now.'?", type: "multiple_choice", correct: "他们都工作了。", options: ["他们工作了都。", "都他们工作了。", "他们都工作了。", "他们都了工作。"] }
  ],

  15: [
    { question: "What does 飞机 mean?", type: "multiple_choice", correct: "Airplane", options: ["Train", "Bus", "Airplane", "Taxi"] },
    { question: "What does 出租车 mean?", type: "multiple_choice", correct: "Taxi", options: ["Bus", "Subway", "Taxi", "Ride-share"] },
    { question: "What does 地铁 mean?", type: "multiple_choice", correct: "Subway / Metro", options: ["Tram", "Monorail", "Subway / Metro", "Train"] },
    { question: "What does 机场 mean?", type: "multiple_choice", correct: "Airport", options: ["Train station", "Bus station", "Airport", "Port"] },
    { question: "What does 坐 mean in transportation?", type: "multiple_choice", correct: "To take (transport) / To ride", options: ["To drive", "To walk", "To take (transport) / To ride", "To fly"] },
    { question: "What does 走 mean?", type: "multiple_choice", correct: "To walk / To go / To leave", options: ["To run", "To walk / To go / To leave", "To stand", "To sit"] },
    { question: "What does 骑 mean?", type: "multiple_choice", correct: "To ride (bike, horse)", options: ["To drive a car", "To take a bus", "To ride (bike, horse)", "To fly"] },
    { question: "What does 北京 mean?", type: "multiple_choice", correct: "Beijing (China's capital)", options: ["Shanghai", "Beijing (China's capital)", "Guangzhou", "Shenzhen"] },
    { question: "What does 票 mean?", type: "multiple_choice", correct: "Ticket", options: ["Money", "ID card", "Ticket", "Receipt"] },
    { question: "What does 远 mean?", type: "multiple_choice", correct: "Far / Distant", options: ["Near", "High", "Far / Distant", "Long"] },
    { question: "What does 近 mean?", type: "multiple_choice", correct: "Near / Close", options: ["Far", "Short", "Near / Close", "Small"] },
    { question: "How do you say 'Take the subway.'?", type: "multiple_choice", correct: "坐地铁", options: ["骑地铁", "走地铁", "坐地铁", "开地铁"] },
    { question: "How do you say 'take a taxi'?", type: "multiple_choice", correct: "坐出租车", options: ["骑出租车", "走出租车", "坐出租车", "开出租车"] },
    { question: "What does 是...的 emphasize in a sentence?", type: "multiple_choice", correct: "HOW, WHEN, or WHERE a past action happened", options: ["Whether an action happened", "HOW, WHEN, or WHERE a past action happened", "Who did the action", "The result of the action"] },
    { question: "Translate: 'I came by airplane.'", type: "multiple_choice", correct: "我是坐飞机来的。", options: ["我坐了飞机来。", "我是坐飞机来的。", "我坐飞机来了。", "我来是坐飞机。"] },
    { question: "How do you ask 'Is the airport far?'", type: "multiple_choice", correct: "机场远不远？", options: ["机场是远吗？", "机场远不远？", "机场有多远？", "机场很远吗？"] },
    { question: "How do you say 'Not far, quite close.'?", type: "multiple_choice", correct: "不远，很近。", options: ["没远，很近。", "不远，很近。", "不远，有近。", "远不，近很。"] },
    { question: "Which verb is used for riding a bicycle?", type: "multiple_choice", correct: "骑", options: ["坐", "走", "骑", "开"] },
    { question: "How do you say 'How do I get to the airport?'", type: "multiple_choice", correct: "去机场怎么走？", options: ["去机场怎么样？", "机场怎么去？", "去机场怎么走？", "Both B and C"] },
    { question: "Translate: 'How did she come?' (method of travel)", type: "multiple_choice", correct: "她是怎么来的？", options: ["她怎么来了？", "她是怎么来的？", "她来怎么了？", "怎么她来了？"] },
    { question: "How do you say 'Buy a ticket'?", type: "multiple_choice", correct: "买票", options: ["有票", "买一票", "买票", "取票"] },
    { question: "What does 怎么去 mean?", type: "multiple_choice", correct: "How to get there / How do you go", options: ["Where to go", "When to go", "How to get there / How do you go", "Why go"] },
    { question: "Translate: 'Go to Beijing by subway.'", type: "multiple_choice", correct: "坐地铁去北京。", options: ["走去北京地铁。", "去坐地铁北京。", "坐地铁去北京。", "北京坐地铁去。"] },
    { question: "What transport uses 骑 instead of 坐?", type: "multiple_choice", correct: "Bicycle / Bike (自行车)", options: ["Taxi", "Airplane", "Bicycle / Bike (自行车)", "Subway"] },
    { question: "Translate: 'The plane ticket is very expensive.'", type: "multiple_choice", correct: "飞机票很贵。", options: ["飞机贵票很。", "很贵飞机票。", "飞机票很贵。", "贵飞机票很。"] }
  ]
};

// ── Write quizzes to lesson files ─────────────────────────────────────────────
let updated = 0;
for (const [lessonNum, quiz] of Object.entries(ALL_QUIZZES)) {
  const filePath = path.join(DATA_DIR, `hsk1_lesson_${lessonNum}.json`);
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  File not found: ${filePath}`);
    continue;
  }
  const lesson = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  lesson.quiz = quiz;
  fs.writeFileSync(filePath, JSON.stringify(lesson, null, 2));
  console.log(`✅  L${lessonNum}: ${quiz.length} questions written`);
  updated++;
}
console.log(`\n🎉  Done! Updated ${updated}/15 lesson files.`);
